const products = [
    {
      id: 1,
      name: "Apelsin",
      price: 3.49,
      image: "img/fruite-item-1.jpg",
      category: "Fruits",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "1kg",
      descriptionDetail: ['The generated Lorem Ipsum is therefore always free from repetition injected humour, or non-characteristic words etc.', 'Susp endisse ultricies nisi vel quam suscipit. Sabertooth peacock flounder; chain pickerel hatchetfish, pencilfish snailfish'],
      countryOfOrigin: "Spain",
      quality: "A",
      check: true,
      minWeight: "500g",
    },
    {
      id: 2,
      name: "Malina",
      price: 2.99,
      image: "img/fruite-item-2.jpg",
      category: "Fruits",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "500g",
      countryOfOrigin: "Poland",
      quality: "A",
      check: true,
      minWeight: "250g",
    },
    {
      id: 3,
      name: "Banan",
      price: 5.49,
      image: "img/fruite-item-3.jpg",
      category: "Fruits",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "1kg",
      countryOfOrigin: "Ecuador",
      quality: "A+",
      check: true,
      minWeight: "500g",
    },
    {
      id: 4,
      name: "O'rik",
      price: 5.49,
      image: "img/fruite-item-4.jpg",
      category: "Fruits",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "500g",
      countryOfOrigin: "Uzbekistan",
      quality: "A",
      check: true,
      minWeight: "250g",
    },
    {
      id: 5,
      name: "Olma",
      price: 5.49,
      image: "img/fruite-item-6.jpg",
      category: "Fruits",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "1kg",
      countryOfOrigin: "USA",
      quality: "A",
      check: true,
      minWeight: "500g",
    },
    {
      id: 6,
      name: "Shaftoli",
      price: 4.99,
      image: "img/fruite-item-7.jpg",
      category: "Fruits",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "1kg",
      countryOfOrigin: "Turkey",
      quality: "A",
      check: true,
      minWeight: "500g",
    },
    {
      id: 7,
      name: "Gilos",
      price: 5.49,
      image: "img/fruite-item-8.jpg",
      category: "Fruits",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "500g",
      countryOfOrigin: "Uzbekistan",
      quality: "A+",
      check: true,
      minWeight: "250g",
    },
    {
      id: 8,
      name: "Anor",
      price: 4.99,
      image: "img/fruite-item-9.jpg",
      category: "Fruits",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "1kg",
      countryOfOrigin: "India",
      quality: "A",
      check: true,
      minWeight: "500g",
    },
    {
      id: 9,
      name: "Apples",
      price: 5.49,
      image: "img/fruite-item-12.jpg",
      category: "Fruits",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "1kg",
      countryOfOrigin: "New Zealand",
      quality: "A+",
      check: true,
      minWeight: "500g",
    },
    {
      id: 10,
      name: "Gulkaram",
      price: 2.49,
      image: "img/vegetables-item-1.jpg",
      category: "Vegetables",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "1kg",
      countryOfOrigin: "Uzbekistan",
      quality: "A",
      check: true,
      minWeight: "500g",
    },
    {
      id: 11,
      name: "Qizil sabzi",
      price: 0.49,
      image: "img/vegetables-item-2.jpg",
      category: "Vegetables",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "1kg",
      countryOfOrigin: "Uzbekistan",
      quality: "A",
      check: true,
      minWeight: "500g",
    },
    {
      id: 12,
      name: "Bodring",
      price: 0.79,
      image: "img/vegetables-item-3.jpg",
      category: "Vegetables",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "1kg",
      countryOfOrigin: "Uzbekistan",
      quality: "A",
      check: true,
      minWeight: "500g",
    },
    {
      id: 13,
      name: "Baqlajon",
      price: 1.09,
      image: "img/vegetables-item-4.jpg",
      category: "Vegetables",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "1kg",
      countryOfOrigin: "Uzbekistan",
      quality: "A",
      check: true,
      minWeight: "500g",
    },
    {
      id: 14,
      name: "Non",
      price: 1.09,
      image: "img/bread-item-1.jpg",
      category: "Bread",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "400g",
      countryOfOrigin: "Uzbekistan",
      quality: "A",
      check: true,
      minWeight: "400g",
    },
    {
      id: 15,
      name: "Shirin non",
      price: 1.09,
      image: "img/bread-item-2.jpg",
      category: "Bread",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "400g",
      countryOfOrigin: "Uzbekistan",
      quality: "A",
      check: true,
      minWeight: "400g",
    },
    {
      id: 16,
      name: "Yumshoq non",
      price: 1.09,
      image: "img/bread-item-3.jpg",
      category: "Bread",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "400g",
      countryOfOrigin: "Uzbekistan",
      quality: "A",
      check: true,
      minWeight: "400g",
    },
    {
      id: 17,
      name: "Yumshoq gosht",
      price: 9.09,
      image: "img/meat-item-1.jpg",
      category: "Meat",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "1kg",
      countryOfOrigin: "Australia",
      quality: "A+",
      check: true,
      minWeight: "500g",
    },
    {
      id: 18,
      name: "Tovuq gosht",
      price: 6.22,
      image: "img/meat-item-2.jpg",
      category: "Meat",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "1kg",
      countryOfOrigin: "Uzbekistan",
      quality: "A",
      check: true,
      minWeight: "500g",
    },
    {
      id: 19,
      name: "Baliq gosht",
      price: 3.09,
      image: "img/meat-item-3.jpg",
      category: "Meat",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "1kg",
      countryOfOrigin: "Norway",
      quality: "A+",
      check: true,
      minWeight: "500g",
    },
    {
      id: 20,
      name: "Qiyma gosht",
      price: 1.09,
      image: "img/meat-item-4.jpg",
      category: "Meat",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "1kg",
      countryOfOrigin: "Uzbekistan",
      quality: "A",
      check: true,
      minWeight: "500g",
    },
    {
      id: 21,
      name: "Qazi",
      price: 2.22,
      image: "img/meat-item-5.jpg",
      category: "Meat",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
      weight: "500g",
      countryOfOrigin: "Uzbekistan",
      quality: "A",
      check: true,
      minWeight: "500g",
    },
  ];